### ISSUE TITLE
'Enable filtering' does not seem to work anymore

### ISSUE THREAD

**Issue by stefantinger** [danielpalme/ReportGenerator#119] opened 2018-01-12 10:31 UTC
Hi!

We are currently using version 3.1.0 for different projects.
In one big project/coverage report (Assemblies: 8; Classes: 2367; Files: 2611; Coverable lines: 421381) clicking the 'Enable filtering' button doesn't do anything anymore.

In another project (much smaller) the 'Enable filtering' button will immediately replaced (without clicking it) with the filter controls and is working fine.

**Comment by danielpalme** [comment] 2018-01-15 12:06
Most likely a duplicate of #116 
If report contains more than 1500 classes, filtering is disabled and you have to activate it via a button click.

Can you send me your reports by mail? danielpalme82@gmail.com

**Comment by stefantinger** [comment] 2018-01-23 16:03
Hi!

If you need a report, i can provide it - but i would need some time to anonymize the data.

Maybe the following info can help you:
"If report contains more than 1500 classes, filtering is disabled and you have to activate it via a button click." - yeah, the problem is, the button does not "activate" the filter controls.

I noticed the following:
I opened the file  directly in the browser (chrome) with "file:///C:/<path>/<summary_report>.htm"
Now when i click the "Enable filtering" button, nothing happens. BUT when i refresh the page now, the filtering controls are visible and work like a charm.

**Comment by danielpalme** [comment] 2018-01-23 16:42
Thanks for the additional hints.

I will try to create a sample report myself. No need to anonymize the data.

**Comment by shunter** [comment] 2018-01-26 15:01
We're seeing the same issue after upgrading from 3.0.2 to 3.1.1. 

I looked through the code briefly though I am not very familiar with Angular but it seems like the issue may be here:

https://github.com/danielpalme/ReportGenerator/blob/master/src/ReportGenerator.Reporting/Rendering/HtmlRenderer.cs#L274

The button runs enableFiltering() but it looks like the function was renamed to enableCoverageTableFiltering here:

https://github.com/danielpalme/ReportGenerator/commit/33a8fb3dcf09dc4a5d72f391f54b3621660c6185#diff-20a7a8b78a1bc53c929edfc516f42bb3L9

**Comment by danielpalme** [comment] 2018-01-26 16:15
@shunter Thanks for your analysis.
Will fix that soon.

**Comment by danielpalme** [comment] 2018-01-26 19:34
Fixed in new release:
https://www.nuget.org/packages/ReportGenerator/3.1.2

**Closed by danielpalme** 2018-01-26 19:34 UTC
Labels: bug
