### ISSUE TITLE
Q: How to include reference to code coverage icon in GitHub markdown?

### ISSUE THREAD

**Issue by ardalis** [danielpalme/ReportGenerator#265] opened 2019-07-11 21:03 UTC
I'm using shields.io to report various metrics on my GitHub repo README.md file. You seem to have a bunch as well. How would I grab the reportgenerator-generated code coverage file from the build results to display, like one of these?

https://shields.io/category/coverage

Looking at your own README I didn't see any reference to such a badge/shield. Thanks!

**Comment by danielpalme** [comment] 2019-07-12 06:56
shields.io provides an image "Azure DevOps coverage". I'm currently using that as a coverage indicator.

In my case:
```
![Coverage](https://img.shields.io/azure-devops/coverage/danielpalme/ReportGenerator/3.svg)
```
![Coverage](https://img.shields.io/azure-devops/coverage/danielpalme/ReportGenerator/3.svg)

_ReportGenerator_ is also able to generate a badges in SVG and PNG format.
If you publish the coverage results (see task `task: PublishCodeCoverageResults@1`), an artifact is generated and you can access the individual files within that artifact by an url like `https://dev.azure.com/danielpalme/_apis/resources/Containers/4421891?itemPath=Code%20Coverage%20Report_254%2Fbadge_combined.svg`

The problem is: This url contains the number that changes on every build. So you can't link to that.

I guess you have to copy/upload the badges to another system to get a static link.

**Comment by ardalis** [comment] 2019-07-12 15:24
Ok, thanks. Yes, I'm using the Azure DevOps badge currently, but was hoping I could put the badges RG produces to good use somehow. Maybe that's something your DevOps extension could support - a standard URL for such things?

**Comment by danielpalme** [comment] 2019-07-12 16:14
I have to read the extension documentation if that is even possible.

**Comment by danielpalme** [comment] 2019-08-30 19:09
I'm closing this for now.
I did not find a way to provide an external url.

**Closed by danielpalme** 2019-08-30 19:09 UTC
Labels: question
