### ISSUE TITLE
ReportGenerator.Core is not compatible with .NET Standard 2.0 anymore

### ISSUE THREAD

**Issue by scsaba** [danielpalme/ReportGenerator#514] opened 2022-04-29 14:56 UTC
When I"m trying to install ReportGenerator.Core 5.1.5 in a netstandard2.0 project, I get the following error:

NU1202: Package McMaster.NETCore.Plugins 1.4.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package McMaster.NETCore.Plugins 1.4.0 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Comment by danielpalme** [comment] 2022-04-29 15:21
Please use 5.1.4 for the moment.
I will fix this in the next release.

**Comment by danielpalme** [comment] 2022-05-01 19:18
Fixed in 5.1.6 (was caused by #508)

**Closed** 2022-05-01 19:21 UTC
Labels: bug
