### ISSUE TITLE
JS Display Issue

### ISSUE THREAD

**Issue by tomap** [danielpalme/ReportGenerator#7] opened 2015-03-05 13:31 UTC
Hi,

I'm investigating this issue, but when using lastest version to produce HTML Reports, the index.html page starts to display just fine, and when it's fully loaded, the javascript kicks in and the whole page is destroyed, emptied, and only a "Enable Filtering" button remains
It happens shortly after a console message "Number of classes (filtering disabled): ... " is displayed
I setup a break point in chrome debugger, but could not understand this issue (after that, it is related to code inside AngularJS and jQuery

Thanks, 

Thomas P.

**Comment by danielpalme** [comment] 2015-03-05 13:44
Hi Thomas,

I have seen this issue just 2 or 3 days ago. It only happens if you have a lot of classes in the summary.
But I did not have the time to investigate this.
I have to debug this to see where it fails.

**Comment by tomap** [comment] 2015-03-05 13:49
Well, that's exactly our case, we have a lot of classes :) (more than 1600)

**Comment by danielpalme** [comment] 2015-03-05 13:54
I will look into that soon.

**Comment by danielpalme** [comment] 2015-03-05 18:43
Fixed with release v.2.1.2.0.

**Comment by SiddhiKK** [comment] 2016-09-29 06:19
Hello,
I am using the version 2.4.5 and I have a bit of similar condition i.e a lot of classes but as the issue is already fixed my html page does work(everything looks great,thanks for that).
 A minor issue that I am seeing is that when the page loads for the first time or every time when I return to it after navigating through different pages, I get only the single button enable filtering(no expand collapse or filtering box options) and i have to click it every time to get back the functionality(see screenshot). 
The functionality is working after clicking the button but it isn't feasible to always click it to get the options back after visiting other pages.(I need to use the options frequently along with navigation).
It would be great if you could fix this one.
Thank you for any help.

This is condition every time I come back to this page.
 
![filteroption](https://cloud.githubusercontent.com/assets/17789419/18942957/26ea569a-863a-11e6-9209-4b6e6b9f05bb.PNG)

And after clicking the button 
![filteroption2](https://cloud.githubusercontent.com/assets/17789419/18943008/81769d12-863a-11e6-8260-863fe0d3a92e.PNG)
:

**Comment by SiddhiKK** [comment] 2016-09-29 07:18
Hello,

Sorry for so many questions, but there is one more issue, when I go to some other link and come back to the main page it expands all the files(it was in collapse all state before navigating) and also if there are some files that I have filtered through search the search results also don't stay(which is okay not the main concern). What I mean to say is that while navigating the state of the main page should be preserved.
As you can see in the screenshot in my previous comment there are a lot of files that I have merged in the report and expanding all of them when coming back to that page takes a toll on the loading time of the report page.
Thank you for the great tool.

**Closed** 2016-09-29 19:53 UTC
Labels: bug, enhancement

**Comment by danielpalme** [comment] 2016-10-24 20:16
@SiddhiKK
The state of the summary page is now stored in history to restore after back navigation.

This feature is available in this beta release:
https://www.nuget.org/packages/ReportGenerator/2.5.0-beta4
